image: golang:1.24

.compose_variables: &compose_variables
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

    # app
    DB_USER: mikhail
    DB_PASS: $DEV_DB_PASS
    DB_HOST: docker
    DB_PORT: 3306
    DB_NAME: test_db
    APP_PORT: 8080

    # mysql container
    DB_ROOT_PASS: $DEV_DB_ROOT_PASS

    # flyway container
    FLYWAY_URL: jdbc:mysql://mysql:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false
    FLYWAY_USER: root
    FLYWAY_PASSWORD: $DEV_DB_ROOT_PASS
    DB_PASS: $DEV_DB_PASS

    COMPOSE_PROJECT_NAME: my-app-go-dev

stages:
  - unit-tests
  - build
  - migrations-test-db
  - ui-tests
  - migrations-prod-db
  - static-analysis
  - deploy
  - release

unit_test:
  stage: unit-tests
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^test.*/ 
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "wip"'
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release.*/
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script: go test -mod=vendor -coverprofile=coverage.out ./repositories/
  artifacts:
    paths:
      - coverage.out

build:
  stage: build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^test.*/ 
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "wip"'
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "wip"
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release.*/'
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release.*/
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script: 
    - CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o my-app-go
  artifacts:
    paths:
      - my-app-go

migrations_test_db:
  <<: *compose_variables
  stage: migrations-test-db
  dependencies:
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^test.*/ 
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "wip"'
  image: docker:28.4.0
  services:
    - name: docker:28.4.0-dind
      alias: docker
  before_script:
    - until docker info > /dev/null 2>&1; do echo "Waiting for Docker..."; sleep 10; done
  script:
    - |
      docker compose \
      -f docker-compose.yml \
      -f docker-compose.ci.yml \
      --profile migrations \
      up \
      --exit-code-from flyway

ui_tests:
  <<: *compose_variables
  stage: ui-tests
  dependencies:
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^test.*/ 
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "wip"'
  image: docker:28.4.0
  services:
    - name: docker:28.4.0-dind
      alias: docker
  before_script:
    - until docker info > /dev/null 2>&1; do echo "Waiting for Docker..."; sleep 10; done
    - docker build -t my-app-go-tmp-image .
  script:
    - |
      docker compose \
      -f docker-compose.yml \
      -f docker-compose.ci.yml \
      --profile migrations \
      up \
      --exit-code-from flyway
    # running app inside container instead of running on the host(job-container) 
    # to get access from Selenium tests container
    - |
      docker run -d \
      --name my-app-go \
      --network ${COMPOSE_PROJECT_NAME}_default \
      -e ENVIRONMENT=dev \
      -e DB_USER=mikhail \
      -e DB_PASS=$DEV_DB_PASS \
      -e DB_HOST=mysql \
      -e DB_PORT=3306 \
      -e DB_NAME=test_db \
      -e APP_PORT=8080 \
      -p 8080:8080 \
      my-app-go-tmp-image
    - |
      docker compose \
      -f docker-compose.yml \
      -f docker-compose.ci.yml \
      --profile ui-tests \
      up \
      --exit-code-from ui-tests

migrations_prod_db:
  extends: .compose_variables
  stage: migrations-prod-db
  dependencies:
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "wip"
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release.*/'
  image: docker:28.4.0
  services:
    - name: docker:28.4.0-dind
      alias: docker
  variables:
    # app
    DB_PASS: $PROD_DB_PASS
    DB_NAME: prod_db

    # mysql container
    DB_ROOT_PASS: $PROD_DB_ROOT_PASS

    # flyway container
    FLYWAY_URL: jdbc:mysql://mysql:3306/prod_db?allowPublicKeyRetrieval=true&useSSL=false
    FLYWAY_PASSWORD: $PROD_DB_ROOT_PASS
    DB_PASS: $PROD_DB_PASS

    COMPOSE_PROJECT_NAME: my-app-go-prod
  before_script:
    - until docker info > /dev/null 2>&1; do echo "Waiting for Docker..."; sleep 10; done
  script:
    - sleep 1
    - |
      docker compose \
      -f docker-compose.yml \
      -f docker-compose.ci.yml \
      --profile migrations \
      up \
      --exit-code-from flyway

sonarqube-check:
  stage: static-analysis
  dependencies:
    - unit_test
  image:
    name: sonarsource/sonar-scanner-cli:12.1
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "1" 
    NODE_OPTIONS: "--max-old-space-size=3072"
    SONAR_SCANNER_OPTS: "-Xmx1536m"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - |
      sonar-scanner \
      -Dsonar.projectKey=root_my-app-go_457e5c30-5356-4727-9db0-bbd4dff6cac0 \
      -Dsonar.sources=. \
      -Dsonar.sourceEncoding=UTF-8 \
      -Dsonar.exclusions="vendor/**,ui-tests/UiTests/bin/**,ui-tests/UiTests/obj/**,godoc/**,certs/**,templates/**,go.mod,go.sum,my-app-go,my-app-go.sln,README.md,systemctl,generate_go_documentation.sh,run-ui-tests.sh" \
      -Dsonar.go.coverage.reportPaths=coverage.out \
      -Dsonar.test.inclusions="**/*_test.go,ui-tests/UiTests/*.cs" \
      -Dsonar.qualitygate.wait=true 
  allow_failure: false
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release.*/
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

deploy:
  stage: deploy
  dependencies:
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release.*/
          && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  image: docker:28.4.0
  services:
    - name: docker:28.4.0-dind
      alias: docker
      command: ["--insecure-registry=gitlab.local:5005"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    REGISTRY_URL: "gitlab.local:5005"
    IMAGE_TAG: $REGISTRY_URL/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  before_script:
    - until docker info > /dev/null 2>&1; do echo "Waiting for Docker..."; sleep 10; done
    - echo "$CI_DEPLOY_PASSWORD" | docker login $REGISTRY_URL -u $CI_DEPLOY_USER --password-stdin
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

generate_docs:
  stage: release
  rules: 
    - if: '$CI_COMMIT_TAG =~ /^release.*/'
  script:
    - go install golang.org/x/tools/cmd/godoc@v0.1.0
    - export PATH="$PATH:/root/go/bin"
    - . generate_go_documentation.sh
    - generate_go_documentation
  artifacts:
    paths:
      - godoc/

pages:
  stage: release
  rules: 
    - if: '$CI_COMMIT_TAG =~ /^release.*/'
  needs:
    - job: generate_docs
  script:
    - mkdir -p public
    - cp -r godoc/* public/
    # redirect from root to index.html
    - echo '<meta http-equiv="refresh" content="0; url=pkg/my-app-go/index.html" />' > public/index.html
  artifacts:
    paths:
      - public

release:
  stage: release
  # custom image with SSL certificates
  image: gitlab.local:5005/root/my-app-go/custom-release-cli:v0.24.0
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release.*/'
  needs:
    - job: generate_docs
  script:
    - echo "Creating GitLab release..."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'