stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    wget https://golang.org/dl/go1.24.linux-amd64.tar.gz &&
    tar -C /usr/local -xzf go1.24.linux-amd64.tar.gz
  script: go test -cover ./repositories/

build:
  stage: build
  before_script:
    wget https://golang.org/dl/go1.24.linux-amd64.tar.gz &&
    tar -C /usr/local -xzf go1.24.linux-amd64.tar.gz
  script: go build -o my-app-go
  artifacts:
    paths:
      - my-app-go

deploy:
  stage: deploy
  before_script:
    wget https://golang.org/dl/go1.24.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.24.linux-amd64.tar.gz
  script: zip my-app-go.zip my-app-go
  dependencies:
    - build
