stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - go build -o my-app-go
  artifacts:
    paths:
      - my-app-go

test-job:
  stage: test
  script:
    - go test -cover ./repositories/
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  script:
    - echo "Деплой приложения..."
    - chmod +x my-app-go
    - ./my-app-go
  dependencies:
    - build-job