services:
  mysql:
    ports:
      - "$DB_PORT:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ./$DB_INIT_SCRIPT_NAME:/docker-entrypoint-initdb.d/$DB_INIT_SCRIPT_NAME

  flyway:
    environment:
      FLYWAY_URL: $FLYWAY_URL
      FLYWAY_USER: $FLYWAY_USER
      FLYWAY_PASSWORD: $FLYWAY_PASSWORD

  selenium-chrome:
    ports:
      - "$SELENIUM_SERVER_PORT:4444"
    environment:
      APP_URL: http://host.docker.internal:${APP_PORT}

  ui-tests:
    environment:
      SELENIUM_SERVER_URI: http://selenium-chrome:4444