services:
  mysql:
    image: mysql:8.0
    container_name: my-app-go-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    ports:
      - "$DB_PORT:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - $PROJECT_PATH/full_dump.sql:/docker-entrypoint-initdb.d/full_dump.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-go
    restart: unless-stopped
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
      DB_NAME: $DB_NAME
    depends_on:
      - mysql
    ports:
      - "8081:8081"

  apache:
    image: httpd:2.4
    container_name: my-app-go-publish-docs
    ports:
      - "8082:80"
    volumes:
      - $DOCS_PATH:/usr/local/apache2/htdocs/

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    network_mode: host

volumes:
  mysql_data: