services:
  apache:
    image: httpd:2.4
    container_name: my-app-go-publish-docs
    ports:
      - "8082:80"
    volumes:
      - $DOCS_PATH:/usr/local/apache2/htdocs/

  selenium-chrome:
      image: selenium/standalone-chrome:latest
      container_name: selenium-chrome
      ports:
        - "4444:4444"
      extra_hosts:
        - "host.docker.internal:host-gateway"