services:
  mysql:
    image: mysql:8.0.42
    container_name: my-app-go-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    volumes:
      - mysql_data:/var/lib/mysql
      - $PROJECT_PATH/full_dump.sql:/docker-entrypoint-initdb.d/full_dump.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-go
    restart: unless-stopped
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
      DB_NAME: $DB_NAME
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env:ro

  apache:
    image: httpd:2.4
    container_name: my-app-go-publish-docs
    ports:
      - "8082:80"
    volumes:
      - $DOCS_PATH:/usr/local/apache2/htdocs/
    profiles: ["docs"]

  selenium-chrome:
    image: selenium/standalone-chrome:4.18.1
    container_name: selenium-chrome
    depends_on:
      - app
    ports:
      - "4444:4444"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles: ["ui-tests"]

volumes:
  mysql_data:


