info:
  contact: {}
  description: API для управления курсами и студентами
  license:
    name: MIT
  title: My CRUD App API
  version: "1.0"
paths:
  /courses:
    get:
      description: загружает HTML-страницу со списком курсов
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает список курсов
      tags:
      - courses
  /courses/create:
    get:
      description: Загружает HTML-страницу с формой для создания нового курса
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму создания курса
      tags:
      - courses
  /courses/delete:
    get:
      description: Удаляет название курса по ID, переданному через query-параметр
      parameters:
      - description: ID курса
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /courses
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удаляет информацию о курсе
      tags:
      - courses
  /courses/edit:
    get:
      description: Загружает HTML-страницу с формой для редактирования информации
        о курсе
      parameters:
      - description: ID курса
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма редактирования
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму редактирования курса
      tags:
      - courses
  /courses/insert:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Получает данные из формы и сохраняет новый курс в базу данных
      parameters:
      - description: Название курса
        in: formData
        name: title
        required: true
        type: string
      - description: ID преподавателя
        in: formData
        name: teacher_id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /courses
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создает новый курс
      tags:
      - courses
  /courses/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Обновляет название курса по ID, переданному через форму
      parameters:
      - description: ID курса
        in: formData
        name: id
        required: true
        type: string
      - description: Новое название курса
        in: formData
        name: title
        required: true
        type: string
      - description: ID преподавателя
        in: formData
        name: teacher_id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /courses
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновляет информацию о курсе
      tags:
      - courses
  /students:
    get:
      description: загружает HTML-страницу со списком студентов
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает список студентов
      tags:
      - students
  /students/create:
    get:
      description: Загружает HTML-страницу с формой для создания нового студента
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму создания студента
      tags:
      - students
  /students/delete:
    get:
      description: Удаляет имя студента по ID, переданному через query-параметр
      parameters:
      - description: ID студента
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /students
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удаляет информацию о студенте
      tags:
      - students
  /students/edit:
    get:
      description: Загружает HTML-страницу с формой для редактирования информации
        о студенте
      parameters:
      - description: ID студента
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма редактирования
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму редактирования студента
      tags:
      - students
  /students/insert:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Получает данные из формы и сохраняет нового студента в базу данных
      parameters:
      - description: Имя студента
        in: formData
        name: name
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /students
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создает нового студента
      tags:
      - students
  /students/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Обновляет имя студента по ID, переданному через форму
      parameters:
      - description: ID студента
        in: formData
        name: id
        required: true
        type: string
      - description: Новое имя студента
        in: formData
        name: name
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /students
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновляет информацию о студенте
      tags:
      - students
  /students_courses:
    get:
      description: загружает HTML-страницу со списком студентов и курсов, которые
        они посещают
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает список студентов и их курсов
      tags:
      - students_courses
  /students_courses/create:
    get:
      description: Загружает HTML-страницу с формой для создания новой записи о студенте
        и курсе, который он посещает
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму создания студентов и их курсов
      tags:
      - students_courses
  /students_courses/delete:
    get:
      description: Удаляет информацию о студенте и курсе, который он посещает, по
        ID студента и ID курса, переданным через query-параметры
      parameters:
      - description: ID студента
        in: query
        name: student_id
        required: true
        type: string
      - description: ID курса
        in: query
        name: course_id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /students_courses
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удаляет информацию о студенте и курсе, который он посещает
      tags:
      - students_courses
  /students_courses/insert:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Получает данные из формы и сохраняет новую запись о студенте и
        курсе, который он посещает, в базу данных
      parameters:
      - description: ID студента
        in: formData
        name: student_id
        required: true
        type: string
      - description: ID курса
        in: formData
        name: course_id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /students_courses
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создает новую запись о студенте и курсе, который он посещает
      tags:
      - students_courses
  /teachers:
    get:
      description: загружает HTML-страницу со списком преподавателей
      produces:
      - text/html
      responses:
        "200":
          description: HTML-страница
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает список преподавателей
      tags:
      - teachers
  /teachers/create:
    get:
      description: Загружает HTML-страницу с формой для создания нового преподавателя
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму создания преподавателя
      tags:
      - teachers
  /teachers/delete:
    get:
      description: Удаляет имя преподавателя по ID, переданному через query-параметр
      parameters:
      - description: ID преподавателя
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /teachers
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удаляет информацию о преподавателе
      tags:
      - teachers
  /teachers/edit:
    get:
      description: Загружает HTML-страницу с формой для редактирования информации
        о преподавателе
      parameters:
      - description: ID преподавателя
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: HTML-форма редактирования
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Отображает форму редактирования преподавателя
      tags:
      - teachers
  /teachers/insert:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Получает данные из формы и сохраняет нового преподавателя в базу
        данных
      parameters:
      - description: Имя преподавателя
        in: formData
        name: name
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /teachers
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создает нового преподавателя
      tags:
      - teachers
  /teachers/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Обновляет имя преподавателя по ID, переданному через форму
      parameters:
      - description: ID преподавателя
        in: formData
        name: id
        required: true
        type: string
      - description: Новое имя преподавателя
        in: formData
        name: name
        required: true
        type: string
      produces:
      - text/html
      responses:
        "303":
          description: Редирект на /teachers
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновляет информацию о преподавателе
      tags:
      - teachers
swagger: "2.0"
